# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
#    allow:
#      # Allow updates for Lodash
#      - dependency-name: "lodash"
#      # Allow updates for React and any packages starting "react"
#      - dependency-name: "react*"
#        versions: ["4.x", "5.x"]
#    assignees:
#      - "ismet55555"
#    reviewers:
#      - "ismet55555"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
