name: YAPF Formatting Check
on: [push, pull_request]
jobs:
  format:
    # Check if the PR is not from a fork
    # if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: yapf
        uses: AlexanderMelde/yapf-action@master
        with:
          args: --recursive --verbose .

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      # - name: Push changes
      #   if: steps.git-check.outputs.modified == 'true'
      #   run: |
      #     git config --global user.name 'YAPF Checker'
      #     git config --global user.email 'YAPF_CHECKER@users.noreply.github.com'
      #     git remote set-url origin https://x-access-token:${{ secrets.YO_JENKINS_YAPF }}@github.com/${{ github.repository }}
      #     git commit -am "YAPF formatting check automated changes"
      #     git push

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.YO_JENKINS_YAPF }}
          branch: ${{ github.ref }}